title: Climate projects
author: Gautam Sisodia
exclude_patterns: 
  - README.md
  - render.py
repository:
  url: https://github.com/gautsi/climate
html:
  use_repository_button: true
execute:
  exclude_patterns:
    - render.py
  execute_notebooks: auto
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
  config:
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py:percent